/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Smurf = {
  _id: string;
  _type: "smurf";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  personality?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Smurf
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/app/queries/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0] {  title,  tagline,  heroImage {    asset,    hotspot,    crop,    alt,    "lqip": asset->metadata.lqip  }}
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      title: null;
      tagline: null;
      heroImage: null;
    }
  | {
      title: string | null;
      tagline: null;
      heroImage: null;
    }
  | {
      title: string | null;
      tagline: string | null;
      heroImage: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        lqip: string | null;
      } | null;
    }
  | null;

// Source: ../web/app/queries/smurfs.ts
// Variable: SMURFS_QUERY
// Query: *[_type == "smurf" && defined(slug.current)] | order(name asc) {  _id,  name,  slug,  personality,  image {  asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip}}
export type SMURFS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  personality: string | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    lqip: string | null;
  } | null;
}>;

// Source: ../web/app/queries/smurfs.ts
// Variable: SMURF_QUERY
// Query: *[_type == "smurf" && slug.current == $slug][0] {  _id,  name,  slug,  personality,  image {  asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip}}
export type SMURF_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  personality: string | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    lqip: string | null;
  } | null;
} | null;

// Source: ../web/app/queries/villageStats.ts
// Variable: VILLAGE_STATS_QUERY
// Query: {  "residents": count(*[_type == "smurf"]),  "portraits": count(*[_type == "smurf" && defined(image.asset)]),  "newest": *[_type == "smurf" && defined(slug.current)] | order(_createdAt desc)[0] {    name,    slug,    _createdAt  },  "lastUpdated": *[_type == "smurf"] | order(_updatedAt desc)[0]._updatedAt}
export type VILLAGE_STATS_QUERY_RESULT = {
  residents: number;
  portraits: number;
  newest: {
    name: string | null;
    slug: Slug | null;
    _createdAt: string;
  } | null;
  lastUpdated: string | null;
};
